apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keyvoro-staging

resources:
  - ../../base
  - ../../externalsecrets/vault.yaml

# Staging-specific patches
patches:
  - target:
      kind: Deployment
      name: keyvoro
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
