apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keyvoro

resources:
- ../../base

# Image tag — updated automatically by CI after each build
images:
- name: ghcr.io/adroiteck-ps/keyvoro
  newTag: git-df05a83

# Production-specific patches
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: keyvoro
